USE biblioteca;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_SAFE_UPDATES = 0;
DROP TABLE IF EXISTS AUTORES;
DROP TABLE IF EXISTS LIBROS;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS VENTAS;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS ALQUILER;

-------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS AUTORES (
id_autor INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Apellido VARCHAR(30) NOT NULL,
id_genero INT NOT NULL,
Nacionalidad VARCHAR(30) NOT NULL,
FOREIGN KEY (id_genero) REFERENCES GENEROS(id_genero)
); 

CREATE TABLE IF NOT EXISTS GENEROS (
id_genero INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre_genero VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIBROS (
id_libros INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_autor INT NOT NULL,
Año INT NOT NULL,
id_genero INT NOT NULL,
Titulo VARCHAR (70),
Stock INT NOT NULL,
FOREIGN KEY (id_autor) REFERENCES AUTORES(id_autor),
FOREIGN KEY (id_genero) REFERENCES GENEROS(id_genero)
);

CREATE TABLE IF NOT EXISTS ALQUILER (
id_alquiler INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_usuario INT NOT NULL,
id_libros INT NOT NULL,
id_genero INT NOT NULL,
Fecha_alquiler DATE NOT NULL,
Fecha_devolucion DATE NOT NULL,
Monto_Facturado FLOAT NOT NULL,
FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario),
FOREIGN KEY (id_libros) REFERENCES LIBROS(id_libros),
FOREIGN KEY (id_genero) REFERENCES GENEROS(id_genero)
);

CREATE TABLE IF NOT EXISTS USUARIOS (
id_usuario INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Apellido VARCHAR(30) NOT NULL,
Edad INT NOT NULL,
Telefono VARCHAR(30) NOT NULL,
Direccion VARCHAR(70) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENTAS (
id_ventas INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_usuario INT NOT NULL,
id_libro INT NOT NULL,
Fecha_venta DATE NOT NULL,
Cantidad INT NOT NULL,
Monto_Facturado FLOAT NOT NULL,
FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario),
FOREIGN KEY (id_libro) REFERENCES LIBROS(id_libros)
);

CREATE TABLE Autor_genero 
(id_autor INT NOT NULL PRIMARY KEY,
id_genero INT NOT NULL
);

CREATE TABLE libro_genero 
(id_libro INT NOT NULL PRIMARY KEY,
id_genero INT NOT NULL
);